vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        member_photo:
            uri_prefix: /images/images/member
            upload_destination: '%kernel.project_dir%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
